name: Linux

on:
  workflow_run:
    workflows: ["Static Analysis"]
    types: 
      - completed

jobs:
  unit_and_acceptance_tests:
    uses: ./.github/workflows/action-base.yml@main
    with:
      # arrays for matrices must be given as string for json parsing
      # https://github.community/t/reusable-workflow-with-strategy-matrix/205676
      os: "[ubuntu-latest]"
      browser: "[chrome, firefox]"
      python-version: "[3.7, 3.8, 3.9]"