name: ${{ github.event.head_commit.message }}

on:
  workflow_run:
    workflows: ["Static Analysis"]
    branches: [master, main]
    types: 
      - completed

jobs:
  Test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/tests-reusable.yml
    with:
      # arrays for matrices must be given as string for json parsing
      # https://github.community/t/reusable-workflow-with-strategy-matrix/205676
      os: '["windows-latest"]'
      browser: '["chrome", "edge", "firefox"]'
      python-version: '["3.9", "3.10"]'
      rfw-322-python: "3.9"
      additional-rfw-parameters: "-e FLASK"